# Generated by CMake, DO NOT EDIT
/Users/sabotage3d/DEV/Urho3D-1.32/ios-Build/CMakeFiles/cmake.check_cache: \
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/CMakeParseArguments.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/FindDoxygen.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/FindPackageMessage.cmake\
/Users/sabotage3d/DEV/Urho3D-1.32/Docs/CMakeLists.txt
	/Applications/CMake\ 2.8-12.app/Contents/bin/cmake -H/Users/sabotage3d/DEV/Urho3D-1.32/Source -B/Users/sabotage3d/DEV/Urho3D-1.32/ios-Build
